# Generated by Django 3.2 on 2021-06-04 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('married', models.IntegerField()),
                ('education', models.IntegerField()),
                ('street', models.CharField(max_length=255)),
                ('str_building_no', models.CharField(max_length=10)),
                ('str_local_no', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
