# Generated by Django 3.2 on 2021-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmodel',
            name='request_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
