# Generated by Django 3.2 on 2021-04-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6, verbose_name='gender')),
                ('married', models.BinaryField(max_length=6, verbose_name='married')),
                ('dependents', models.IntegerField(max_length=10, verbose_name='Dependents')),
                ('education', models.CharField(max_length=25, verbose_name='Education')),
                ('self_employed', models.BinaryField(max_length=6, verbose_name='Self_Employed')),
                ('applicant_income', models.IntegerField(max_length=6, verbose_name='ApplicantIncome')),
                ('coapplicant_income', models.IntegerField(max_length=6, verbose_name='CoapplicantIncome')),
                ('loan_amount', models.IntegerField(max_length=6, verbose_name='LoanAmount')),
                ('loan_amount_term', models.IntegerField(max_length=6, verbose_name='Loan_Amount_Term')),
                ('credit_history', models.CharField(max_length=6, verbose_name='Credit_History')),
                ('property_area', models.CharField(max_length=6, verbose_name='Property_Area')),
            ],
        ),
    ]
