# Generated by Django 3.2 on 2021-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='applicant_income',
            field=models.IntegerField(verbose_name='ApplicantIncome'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='coapplicant_income',
            field=models.IntegerField(verbose_name='CoapplicantIncome'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='dependents',
            field=models.IntegerField(verbose_name='Dependents'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='loan_amount',
            field=models.IntegerField(verbose_name='LoanAmount'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='loan_amount_term',
            field=models.IntegerField(verbose_name='Loan_Amount_Term'),
        ),
    ]
